---
# Setup cobbler for hosts to provisione

- include_tasks: backends/vmware/cobbler.yml
  when: hostvars.localhost.host_provisioner_vmware_server is defined

- name: Setup cobbler for hosts to provisione
  include_role:
    name: amtega.cobbler
    public: yes
    apply:
      delegate_to: "{{ host_provisioner_cobbler_server }}"
      delegate_facts: yes
  vars:
    cobbler_delete_unmanaged: no
    cobbler_systems: >-
      {{ hostvars.localhost.host_provisioner_vmware_cobbler_systems
         | map("combine", { "state": host_provisioner_cobbler_systems_state })
         | list }}

- meta: flush_handlers
