---
# End configuration of provisioned hosts

- name: Pause after applying ansible
  ansible.builtin.pause:
    seconds: "{{ host_provisioner_after_ansible_pause }}"

- name: Release dhcp address
  ansible.builtin.command: /usr/sbin/dhclient -r
  changed_when: yes

- name: Halt provisioned hosts
  ansible.builtin.shell: >-
    sleep 3
    && /usr/sbin/shutdown -h now 'Ansible triggered a halt'
  args:
    warn: no
  async: 1
  poll: 0
  changed_when: yes
  ignore_errors: yes # noqa ignore-errors
