---
# Start configuration of provisioned hosts

- ansible.builtin.include_tasks: backends/vmware/nics.yml
  when: hostvars.localhost.host_provisioner_vmware_server is defined

- name: Pause before applying ansible
  ansible.builtin.pause:
    seconds: "{{ host_provisioner_before_ansible_pause }}"
