---
# End configuration of provisioned hosts

- name: Pause after applying ansible
  pause:
    seconds: "{{ host_provisioner_after_ansible_pause }}"

- name: Release dhcp address
  command: /usr/sbin/dhclient -r
  changed_when: yes

- name: Halt provisioned hosts
  shell: >-
    sleep 3
    && /usr/sbin/shutdown -h now 'Ansible triggered a halt'
  args:
    warn: no
  async: 1
  poll: 0
  changed_when: true
  ignore_errors: true # noqa ignore-errors
