---
# Role tasks

- name: Provisione hosts
  block:
    - name: Setup fact to optimize further runs
      ansible.builtin.set_fact:
        host_provisioner_deps_resolved: yes

    - ansible.builtin.include_tasks: stalled.yml
      when:
        - host_provisioner_stage == "cleanup_stalled"

    - name: Create host and setup dhcpd / cobber
      block:
        - ansible.builtin.include_tasks: create.yml
          when: host_provisioner_stage == "provisione"

        - ansible.builtin.include_tasks: dhcpd.yml
          when: host_provisioner_stage == "setup_dhcp"
          vars:
            host_provisioner_dhcpd_hosts_state: present

        - ansible.builtin.include_tasks: cobbler.yml
          when: host_provisioner_stage == "setup_cobbler"
          vars:
            host_provisioner_cobbler_systems_state: present
      when:
        - >-
          hostvars.localhost.host_provisioner_vmware_vms_filtered.to_provisione
          | length > 0

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Install and configure host
      block:
        - ansible.builtin.include_tasks: install.yml
          when: host_provisioner_stage == "install"

        - ansible.builtin.include_tasks: inventory.yml
          when: host_provisioner_stage == "inventory"

        - ansible.builtin.include_tasks: wait.yml
          when: host_provisioner_stage == "wait"

        - ansible.builtin.include_tasks: configure_start.yml
          when: host_provisioner_stage == "configure_start"

        - ansible.builtin.include_tasks: configure_end.yml
          when: host_provisioner_stage == "configure_end"

        - ansible.builtin.include_tasks: finalize.yml
          when: host_provisioner_stage == "finalize"

        - ansible.builtin.include_tasks: dhcpd.yml
          vars:
            host_provisioner_dhcpd_hosts_state: absent     ,
          when: host_provisioner_stage == "cleanup_dhcp"

        - ansible.builtin.include_tasks: cobbler.yml
          vars:
            host_provisioner_cobbler_systems_state: absent
          when: host_provisioner_stage == "cleanup_cobbler"
      when:
        - >-
          hostvars.localhost.host_provisioner_vmware_vms_filtered.to_provisione
          | length > 0
  tags:
    - role::host_provisioner
