---
# Role tasks

- include_tasks: stalled.yml
  when: host_provisioner_stage == "cleanup_stalled"

- include_tasks: create.yml
  when: host_provisioner_stage == "provisione"

- include_tasks: dhcpd.yml
  when: host_provisioner_stage == "setup_dhcp"
  vars:
    host_provisioner_dhcpd_hosts_state: present

- include_tasks: cobbler.yml
  when: host_provisioner_stage == "setup_cobbler"

- include_tasks: install.yml
  when: host_provisioner_stage == "install"

- include_tasks: inventory.yml
  when: host_provisioner_stage == "inventory"

- include_tasks: wait.yml
  when: host_provisioner_stage == "wait"

- include_tasks: configure.yml
  when: host_provisioner_stage == "configure"



# - include_tasks: finalize.yml
#
# - include_tasks: dhcpd.yml
#   vars:
    # host_provisioner_dhcpd_hosts_state: absent
