---
# Setup facts to manage VMware provisioned hosts with cobbler

- name: Setup facts to manage VMware provisioned hosts with cobbler
  ansible.builtin.set_fact:
    host_provisioner_cobbler_server: "{{ inventory_hostname }}"
    host_provisioner_vmware_cobbler_systems: >-
      {{ host_provisioner_vmware_cobbler_systems }}
    host_provisioner_cobbler_systems: >-
      {{ host_provisioner_cobbler_systems
         | default([])
         + host_provisioner_vmware_cobbler_systems }}
  delegate_to: localhost
  delegate_facts: yes
  vars:
    host_provisioner_vmware_cobbler_systems: >-
      {{ lookup('template', 'backends/vmware/cobbler.yml.j2') | from_yaml }}
