---
# Setup facts to manage VMware provisioend hosts with cobbler

- name: Setup facts to manage VMware provisioend hosts with cobbler
  set_fact:
    host_provisioner_cobbler_server: "{{ inventory_hostname }}"
    host_provisioner_vmware_cobbler_systems: >-
      {{ lookup('template', 'backends/vmware/cobbler.yml.j2') | from_yaml }}
  delegate_to: localhost
  delegate_facts: yes
