---
# Create VMWare hosts and setup related facts

- name: Create VMware hosts
  ansible.builtin.include_role:
    name: amtega.vmware_provisioner
    public: yes
  vars:
    vmware_provisioner_gather_all_basic_vm_facts: no
    vmware_provisioner_gather_datacenters_info: no
    vmware_provisioner_gather_clusters_info: no
    vmware_provisioner_gather_datastores_info: no
    vmware_provisioner_gather_folders_info: no
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >-
      {{ lookup("template", "backends/vmware/vms_provisioning.yml.j2")
         | from_yaml }}
    vmware_provisioner_provisione: yes

- name: Setup facts to manage created VMware hosts mac addresses
  ansible.builtin.set_fact:
    host_provisioner_vmware_server: "{{ inventory_hostname }}"
    host_provisioner_vmware_macs: "{{ host_provisioner_vmware_macs }}"
    host_provisioner_macs: >-
      {{ host_provisioner_macs
         | default({})
         | combine(host_provisioner_vmware_macs) }}
  delegate_to: localhost
  delegate_facts: yes
  vars:
    host_provisioner_vmware_macs: >-
      {{ lookup("template", "backends/vmware/macs.yml.j2") | from_yaml }}
