---
# Create VMWare hosts and setup related facts

- name: Create VMware hosts
  include_role:
    name: amtega.vmware_provisioner
    public: yes
  vars:
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >-
      {{ hostvars.localhost.host_provisioner_vmware_vms_filtered.to_provisione
         | map("combine", host_provisioner_vmware_vm_overrides)
         | list }}
    vmware_provisioner_provisione: yes

- name: Setup facts to manage created VMware hosts mac addresses
  set_fact:
    host_provisioner_vmware_server: "{{ inventory_hostname }}"
    host_provisioner_vmware_macs: >-
      {{ lookup("template", "backends/vmware/macs.yml.j2") | from_yaml }}
  delegate_to: localhost
  delegate_facts: yes
