---
# Finalize VMware hosts provisioning

- name: Finalize VMware hosts config
  ansible.builtin.include_role:
    name: amtega.vmware_provisioner
    public: yes
  vars:
    vmware_provisioner_gather_all_basic_vm_facts: no
    vmware_provisioner_gather_datacenters_info: no
    vmware_provisioner_gather_clusters_info: no
    vmware_provisioner_gather_datastores_info: no
    vmware_provisioner_gather_folders_info: no
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >-
      {{ lookup("template", "backends/vmware/vms_final.yml.j2")
         | from_yaml
         | map("combine", {"state": "present"})
         | list }}
    vmware_provisioner_provisione: yes
    vmware_provisioner_vm_manage_disk: no

- name: Finalize WMware hosts provisioning
  ansible.builtin.include_role:
    name: amtega.vmware_provisioner
    public: yes
  vars:
    vmware_provisioner_gather_all_basic_vm_facts: no
    vmware_provisioner_gather_datacenters_info: no
    vmware_provisioner_gather_clusters_info: no
    vmware_provisioner_gather_datastores_info: no
    vmware_provisioner_gather_folders_info: no
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >-
      {{ lookup('template', 'backends/vmware/vms_final.yml.j2') | from_yaml }}
    vmware_provisioner_provisione: yes
    vmware_provisioner_vm_manage_disk: no
