---
# Finalize VMware hosts provisioning

- name: Finalize VMware hosts config
  include_role:
    name: amtega.vmware_provisioner
    public: yes
  vars:
    vmware_provisioner_gather_all_basic_vm_fact: no
    vmware_provisioner_gather_datacenters_fact: no
    vmware_provisioner_gather_clusters_fact: no
    vmware_provisioner_gather_datastores_fact: no
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >-
      {{ lookup("template", "backends/vmware/vms.yml.j2")
         | from_yaml
         | map("combine", { "state": "present" })
         | list }}
    vmware_provisioner_provisione: yes

- name: Finalize WMware hosts provisioning
  include_role:
    name: amtega.vmware_provisioner
    public: yes
  vars:
    vmware_provisioner_gather_all_basic_vm_fact: no
    vmware_provisioner_gather_datacenters_fact: no
    vmware_provisioner_gather_clusters_fact: no
    vmware_provisioner_gather_datastores_fact: no
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >-
      {{ lookup('template', 'backends/vmware/vms.yml.j2') | from_yaml }}
    vmware_provisioner_provisione: yes
