---
# Finalize VMware hosts provisioning

- name: Finalize VMware hosts config
  include_role:
    name: amtega.vmware_provisioner
    public: yes
  vars:
    vmware_provisioner_gather_all_basic_vm_facts: no
    vmware_provisioner_gather_datacenters_info: no
    vmware_provisioner_gather_clusters_info: no
    vmware_provisioner_gather_datastores_info: no
    vmware_provisioner_gather_folders_info: no
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >-
      {{ lookup("template", "backends/vmware/vms_final.yml.j2")
         | from_yaml
         | map("combine", {"state": "present", "disk": omit})
         | list }}
    vmware_provisioner_provisione: yes

- name: Finalize WMware hosts provisioning
  include_role:
    name: amtega.vmware_provisioner
    public: yes
  vars:
    vmware_provisioner_gather_all_basic_vm_facts: no
    vmware_provisioner_gather_datacenters_info: no
    vmware_provisioner_gather_clusters_info: no
    vmware_provisioner_gather_datastores_info: no
    vmware_provisioner_gather_folders_info: no
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >-
      {{ lookup('template', 'backends/vmware/vms_final.yml.j2')
         | from_yaml
         | map("combine", {"disk": omit})
         | list }}
    vmware_provisioner_provisione: yes
