---
# Power on VMware hosts to provisione

- name: Power on provisioned hosts vmware virtual machines
  ansible.builtin.include_role:
    name: amtega.vmware_provisioner
    public: yes
  vars:
    vmware_provisioner_gather_all_basic_vm_facts: no
    vmware_provisioner_gather_datacenters_info: no
    vmware_provisioner_gather_clusters_info: no
    vmware_provisioner_gather_datastores_info: no
    vmware_provisioner_gather_folders_info: no
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >
      {{ lookup("template", "backends/vmware/vms_provisioning.yml.j2")
         | from_yaml
         | map("combine", {"state": "poweredon"})
         | list }}
    vmware_provisioner_provisione: yes

- name: Pause to give time to the new VMware hosts dhcp client
  ansible.builtin.pause:
    seconds: "{{ host_provisioner_vmware_dhcp_pause }}"
  delegate_to: "{{ hostvars.localhost.host_provisioner_vmware_server }}"
  delegate_facts: yes
