---
# Power on VMware hosts to provisione

- name: power on provisioned hosts vmware virtual machines
  include_role:
    name: amtega.vmware_provisioner
    apply:
      delegate_to: "{{ host_provisioner_vmware_server }}"
  vars:
    vmware_provisioner_vms: >
      {{ host_provisioner_vmware_vms_filtered.to_provisione
         | map("combine", host_provisioner_vmware_vm_overrides)
         | map("combine", { "state": "poweredon" })
         | list }}

- name: pause to give time to the new VMware hosts dhcp client
  pause:
    seconds: "{{ host_provisioner_vmware_dhcp_pause }}"
  delegate_to: "{{ host_provisioner_vmware_server }}"
