---
# Remove stalled vmware hosts and setup related facts

- name: Setup facts with VMware server
  ansible.builtin.set_fact:
    host_provisioner_vmware_server: "{{ inventory_hostname }}"
  delegate_to: localhost
  delegate_facts: yes

- name: Setup facts with filtered VMware hosts
  ansible.builtin.set_fact:
    host_provisioner_vmware_vms_filtered: >-
      {{ host_provisioner_vmware_vms_filtered }}

    host_provisioner_vms_filtered: >-
      {{ host_provisioner_vms_filtered
         | default({})
         | combine(host_provisioner_vmware_vms_filtered,
                   recursive=True,
                   list_merge="append") }}
  delegate_to: localhost
  delegate_facts: yes
  vars:
    host_provisioner_vmware_vms_filtered: >-
      {{ lookup('template', 'backends/vmware/filter.yml.j2') | from_yaml }}

- name: Remove stalled VMware hosts
  ansible.builtin.include_role:
    name: amtega.vmware_provisioner
    public: yes
  when: >-
    hostvars.localhost.host_provisioner_vmware_vms_filtered.stalled | length > 0
  vars:
    vmware_provisioner_gather_datacenters_info: no
    vmware_provisioner_gather_clusters_info: no
    vmware_provisioner_gather_datastores_info: no
    vmware_provisioner_gather_folders_info: no
    vmware_provisioner_gather_inventory_vm_configs: no
    vmware_provisioner_vms: >-
      {{ hostvars.localhost.host_provisioner_vmware_vms_filtered.stalled
         | map("combine", {"state": "absent"})
         | list }}
    vmware_provisioner_provisione: yes
