---

- name: Cleanup stalled hosts and provisione the new ones
  hosts: testing_backends_host
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: cleanup_stalled

    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: provisione

- name: Setup dhcp entries for provisioned hosts
  hosts: testing_dhcpd_host
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: setup_dhcp

- name: Setup cobbler entities for provisioned hosts
  hosts: testing_cobbler_host
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: setup_cobbler

- name: Install new provisioned hosts
  hosts: testing_backends_host
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: install

- name: Inventory new provisioned hosts
  hosts: testing_backends_host
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: inventory

- name: Wait for new provisioned hosts to be installed
  hosts: testing_backends_host
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: wait

- name: Start configuration of new provisioned hosts
  hosts: >-
    {{ hostvars[groups.testing_backends_host | first].host_provisioner_group }}
  gather_facts: no
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: configure_start

- name: End configuration of new provisioned hosts
  hosts: >-
    {{ hostvars[groups.testing_backends_host | first].host_provisioner_group }}
  gather_facts: no
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: configure_end

- name: Finalize provisioned hosts
  hosts: testing_backends_host
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: finalize

- name: Cleanup dhcp entries used to provisione hosts
  hosts: testing_dhcpd_host
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: cleanup_dhcp

- name: Cleanup cobbler entries used to provisione hosts
  hosts: testing_cobbler_host
  roles:
    - role: amtega.host_provisioner
      vars:
        host_provisioner_stage: cleanup_cobbler
